services:
  db:
    container_name: jacked-db
    image: docker.io/bitnami/postgresql:17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "jacked:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=jacked
      - POSTGRESQL_PASSWORD=jacked
      - POSTGRESQL_DATABASE=jacked
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - jacked

networks:
  jacked:
    driver: bridge

volumes:
  jacked:
    driver: local
